# Generated by Django 2.2.2 on 2019-09-16 08:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emyxin', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='checkinlist',
            options={'ordering': ['created_time']},
        ),
        migrations.RenameField(
            model_name='checkinlist',
            old_name='created',
            new_name='created_time',
        ),
        migrations.RenameField(
            model_name='checkinlist',
            old_name='owner',
            new_name='singner',
        ),
    ]
