# Generated by Django 2.2.2 on 2019-10-25 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emyxin', '0002_auto_20190916_0824'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkinlist',
            name='teacher',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
