# Generated by Django 2.2.2 on 2019-12-16 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emyxin', '0003_checkinlist_teacher'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkinlist',
            name='unid',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
