# Generated by Django 2.2.2 on 2019-12-16 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emyxin', '0004_checkinlist_unid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkinlist',
            name='unid',
            field=models.CharField(blank=True, default='', max_length=1000),
        ),
    ]
